exam/urls.py
from django.urls import path, re_path, include
from exam.views import *

urlpatterns = [
    path('teacherindex', GetTeacherIndex.as_view(), name="index"),
    path('banks', GetQuestionBank.as_view(), name='getbank'),
    path('addbank', AddQuestionBank.as_view(), name='addbank'),
    path('deletebank', DeleteQuestionBank.as_view(), name='deletebank'),
    path('questions', GetQuestions.as_view(), name='getquestion'),
    path('addquestion', AddQuestion.as_view()),
    path('importquestion', BatchAddQuestion.as_view()),
    path('getquestion', GetQuestion.as_view()),
    path('deletetopicimg', DeleteTopicImg.as_view()),
    path('deletequestion', DeleteQuestion.as_view()),
    re_path('searchquestion/(?P<slug>[0-9]{10})', SearchQuestion.as_view(), name='search_question'),
    path('exams', GetExaminationList.as_view(), name='exams'),
    # path('exameditor', ExamEditor.as_view(), name='exameditor'),
    re_path('exameditor/(?P<exam_uuid>[a-z0-9]{0,10})', ExamEditor.as_view(), name='exameditor'),
    re_path('examdesign/(?P<exam_uuid>[a-z0-9]{10})', ExamDesign.as_view(), name='examdesign'),
    path('getSelectQuestions', GetSelectQuestions.as_view()),
    path('selectquestions', SelectQuestionsAjax.as_view()),
    path('setstaticquestionscore', SetStaticQuestionScore.as_view()),
    path('deletestaticquestion', DeleteStaticQuestion.as_view()),
    path('addrandomnode', AddRandomNodeAjax.as_view()),
    path('questiontypechange', QuestionTypeChange.as_view()),
    path('questionbankchange', QuestionBankChange.as_view()),
    path('questionnumberset', QuestionNumberSet.as_view()),
    path('questionscoreset', QuestionScoreSet.as_view()),
    path('deleterandomnode', DeleteRandomNodeAjax.as_view()),
    re_path('exampublish/(?P<exam_uuid>[a-z0-9]{10})', ExamPublish.as_view(), name='examdpublish'),
    re_path('examvisible/(?P<exam_uuid>[a-z0-9]{10})', AllowStudentsVisible.as_view(), name='examvisible'),
    re_path('examdelete/(?P<exam_uuid>[a-z0-9]{10})', DeleteExamination.as_view(), name='examdelete'),
    path('studentindex', GetStudentIndex.as_view(), name='student_index'),
    re_path('exam_paper/(?P<examiner_uuid>[a-z0-9]{10})', StartExam.as_view(), name='exampaper'),
    re_path('examhistorypapers/(?P<exam_uuid>[a-z0-9]{10})', GetAllStudentsPaper.as_view(), name='historypaperlist'),
    path('historyexam', GetHistoryExam.as_view(), name='history'),
    re_path('history_paper/(?P<examiner_uuid>[a-z0-9]{10})', GetHistoryPaper.as_view(), name='historypaper'),
]

onlineTestSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from role.views import Index, page_not_found
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', Index.as_view(), name="index"),
    re_path('^role/', include(('role.urls', 'role'), namespace='role')),
    re_path('^exam/', include(('exam.urls', 'exam'), namespace='exam')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

handler404 = page_not_found

role/urls.py
from django.urls import path, re_path, include
from role.views import *

urlpatterns = [
    path('logout', LoginOut.as_view(), name="logout"),
    path('get_valid_img', GetValidImg.as_view(), name='get_valid_img'),
    path('students', GetStudentInfo.as_view(), name='students'),
    path('addStudent', AddStudentInfo.as_view(), name='addStudent'),
    re_path('downloadexcel/(?P<excel_id>[a-z0-9]{1,10})', DownloadExcelTemplate.as_view(), name='downloadexcel'),
    path('uploadstudentfile', BatchAddStudents.as_view()),
    path('searchStudent', SearchStudentInfo.as_view(), name='searchStudent'),
    path('changeStudentStatus', ChangeStudentStatus.as_view()),
    path('editorStudentInfo', EditorStudentInfo.as_view()),
    path('deleteStudentInfo', DeleteStudentInfo.as_view()),
]

exam/models.py
from django.db import models
from role.models import User
import django.utils.timezone as timezone
from django.db.models import Sum, Count
import datetime
from django.core.exceptions import ValidationError
from role.save import newStorage
import re
import collections
import random
# Create your models here.

letter = ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
weight = [2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]


class QuestionBank(models.Model):
    type_choice = (
        (u'mc', u'单项选择题'),
        (u'mcs', u'多项选择题'),
        (u'tf', u'判断题'),
    )

    creator = models.ForeignKey(User, verbose_name='创建者', related_name="creator_to", on_delete=models.CASCADE)
    uuid = models.CharField('ID', max_length=12)
    name = models.CharField('题库名称', max_length=50)
    type = models.CharField('题库类型', max_length=6, choices=type_choice, default='mc', blank=False)
    count = models.PositiveIntegerField('题目数量', default=0)
    intro = models.CharField('简介', max_length=300, blank=True)
    status = models.BooleanField('是否生效', default=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    def _create_bank_uuid(self):
        year = str(datetime.date.today().year)
        while True:
            uid = year + "".join([str(random.randint(0, 9)) for i in range(6)])
            if not QuestionBank.objects.filter(uuid=uid):
                break
        return uid

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.uuid:
            self.uuid = self._create_bank_uuid()
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    class Meta:
        verbose_name = '题库信息'
        verbose_name_plural = '题库信息管理'
        ordering = ("-last_modified_time", "-created_time")

    def __str__(self):
        return self.name


class SingleQuestion(models.Model):
    uuid = models.CharField('ID', max_length=12)
    bank = models.ForeignKey(QuestionBank, verbose_name='题库', related_name="bank_to", on_delete=models.CASCADE)
    topic = models.TextField('题干', null=False, max_length=1000)
    answer = models.CharField('答案', max_length=5)
    analysis = models.TextField('试题解析', blank=True)
    option_a = models.CharField('A', max_length=300)
    option_b = models.CharField('B', max_length=300)
    option_c = models.CharField('C', max_length=300, null=True, blank=True)
    option_d = models.CharField('D', max_length=300, null=True, blank=True)
    option_e = models.CharField('E', max_length=300, null=True, blank=True)
    option_f = models.CharField('F', max_length=300, null=True, blank=True)
    status = models.BooleanField('是否生效', default=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    def _create_singel_question_uuid(self):
        begin = 'mc'
        while True:
            uid = begin + "".join(random.choices(letter, weight, k=6))
            if not SingleQuestion.objects.filter(uuid=uid):
                break
        return uid

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.uuid:
            self.uuid = self._create_singel_question_uuid()
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    def clean(self):
        if self.answer.upper() not in ['A', 'B', 'C', 'D', 'E', 'F']:
            raise ValidationError({'answer': ('答案不符合要求,请填入字母A-F中一个',)})

    def get_img_topic(self):
        imgs = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='TOPIC')
        return imgs

    def get_img_a(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='A')
        return img

    def get_img_b(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='B')
        return img

    def get_img_c(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='C')
        return img

    def get_img_d(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='D')
        return img

    def get_img_e(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='E')
        return img

    def get_img_f(self):
        img = SingleQuestionImg.objects.filter(question__uuid=self.uuid, choice='F')
        return img

    class Meta:
        verbose_name = '单项选择题信息管理'
        verbose_name_plural = '单项选择题信息管理'
        ordering = ("-last_modified_time", "-created_time")

    def __str__(self):
        return str(self.id)


class SingleQuestionImg(models.Model):
    type_choice = (
        (u'TOPIC', u'题干'),
        (u'A', u'A'),
        (u'B', u'B'),
        (u'C', u'C'),
        (u'D', u'D'),
        (u'E', u'E'),
        (u'F', u'F'),
    )
    question = models.ForeignKey(SingleQuestion, verbose_name='题目',
                                 related_name='single_question_to', on_delete=models.CASCADE)
    choice = models.CharField('对应选项', choices=type_choice, max_length=5, null=False)
    intro = models.CharField('图名', max_length=300, blank=True)
    img = models.ImageField('图片', null=False, upload_to='question/%Y/%m/', storage=newStorage())
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '单选题图片信息'
        verbose_name_plural = '单选题图片信息管理'
        ordering = ("-last_modified_time", "-created_time")


class MultipleQuestion(models.Model):
    uuid = models.CharField('ID', max_length=12)
    bank = models.ForeignKey(QuestionBank, verbose_name='题库', related_name="multiple_bank_to", on_delete=models.CASCADE)
    topic = models.TextField('题干', null=False, max_length=1000)
    answer = models.CharField('答案', max_length=5)
    analysis = models.TextField('试题解析', blank=True)
    option_a = models.CharField('A', max_length=300)
    option_b = models.CharField('B', max_length=300)
    option_c = models.CharField('C', max_length=300, null=True, blank=True)
    option_d = models.CharField('D', max_length=300, null=True, blank=True)
    option_e = models.CharField('E', max_length=300, null=True, blank=True)
    option_f = models.CharField('F', max_length=300, null=True, blank=True)
    status = models.BooleanField('状态', default=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)\


    def _create_multiple_question_uuid(self):
        begin = 'mcs'
        while True:
            uid = begin + "".join(random.choices(letter, weight, k=5))
            if not MultipleQuestion.objects.filter(uuid=uid):
                break
        return uid

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.uuid:
            self.uuid = self._create_multiple_question_uuid()
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    def clean(self):
        counts = collections.Counter(self.answer.upper())
        if not re.match("[A-F]{1,6}", self.answer.upper()) or max(counts.values()) > 1:
            raise ValidationError({'answer': ('答案不符合要求,请填入字母A-F中一个或多个，不可重复',)})

    def get_img_topic(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='TOPIC')
        return imgs

    def get_img_a(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='A')
        return imgs

    def get_img_b(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='B')
        return imgs

    def get_img_c(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='C')
        return imgs

    def get_img_d(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='D')
        return imgs

    def get_img_e(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='E')
        return imgs

    def get_img_f(self):
        imgs = MultipleQuestionImg.objects.filter(question__uuid=self.uuid, choice='F')
        return imgs

    class Meta:
        verbose_name = '多项选择题信息'
        verbose_name_plural = '多项选择题信息管理'
        ordering = ("-last_modified_time", "-created_time")

    def __str__(self):
        return str(self.id)


class MultipleQuestionImg(models.Model):
    type_choice = (
        (u'TOPIC', u'题干'),
        (u'A', u'A'),
        (u'B', u'B'),
        (u'C', u'C'),
        (u'D', u'D'),
        (u'E', u'E'),
        (u'F', u'F'),
    )
    question = models.ForeignKey(MultipleQuestion, verbose_name='题目',
                                 related_name='multiple_question', on_delete=models.CASCADE)
    choice = models.CharField('对应选项', choices=type_choice, max_length=5, null=False)
    intro = models.CharField('图名', max_length=300, blank=True)
    img = models.ImageField('图片', null=False)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '多项选择题图片信息'
        verbose_name_plural = '多项选择题图片信息管理'
        ordering = ("-last_modified_time", "-created_time")


class JudgeQuestion(models.Model):
    answer_choice = (
        (u'1', u'正确'),
        (u'0', u'错误'),
    )
    uuid = models.CharField('ID', max_length=12)

templates/exam/banks.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="shortcut icon" href="#"/>
		<title>题库列表</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/conservator.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bank_list.css' %}"/>
		<link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_1713310_k1bxcvlffm.css"/>
		<script src="{% static 'js/jquery-3.1.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="manage-top">
			<p>在线考试系统教师管理</p>
				
			<div>
			    <span>
			    	<a class="a1" href="javascript:void(0)"><img src="{{ user.head_img.url }}"><font>{{ user.name }}</font></a>
			    	<ul style="display: none;">
{#			    		<li><a href="#"><i class="iconfont icon-people1"></i>个人中心</a></li>#}
{#			    		<li><a href="#"><i class="iconfont icon-password"></i>修改密码</a></li>#}
			    		<li><a href="{% url 'role:logout' %}"><i class="iconfont icon-logout1"></i>退出登录</a></li>
			    	</ul>
			    </span>
		   </div>
			
		</div>
		<div class="manage-content">
			<div class="mc-left">
				<div class="menuList">
					<ul class="menu1">
						<li class="menuli1">
							<a href="{% url 'exam:index' %}" class="menua1">
								<i class="iconfont icon-home1 left"></i>
								<p>教师管理主页</p>
							</a>

						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-candidates left"></i>
								<p>考生管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'role:students' %}" class="menua2">考生信息</a></li>
								<li class="menuli2"><a href="{% url 'role:addStudent' %}" class="menua2">添加考生</a></li>
								<li class="menuli2"><a href="{% url 'role:searchStudent' %}" class="menua2">查询信息</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1 active-menu">
								<i class="iconfont icon-tiku1 left"></i>
								<p>题库管理</p>
								<i class="iconfont icon-bottom right"></i>
							</a>
							<ul class="menu2" style="display: block;">
								<li class="menuli2"><a href="{% url 'exam:getbank' %}" class="menua2 active-menu">题库列表</a></li>
								<li class="menuli2"><a href="{% url 'exam:addbank' %}" class="menua2">添加题库</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-fenshijuan left"></i>
								<p>考试管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:exams' %}" class="menua2">考试信息</a></li>
								<li class="menuli2"><a href="{% url 'exam:exameditor' '' %}" class="menua2">添加考试</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="mc-right">
				<div class="mc-title">
					<font><a>题库管理</a><a>&gt;</a><a>题库列表</a></font>
				</div>
				<div class="mc-body" style="max-height: 525px;overflow-y: scroll">
					<div class="mc-list">
						<table class="mc-table">
							<thead>
								<tr>
									<th style="min-width: 90px;">题库编号</th>
									<th style="min-width: 110px;">题库名称</th>
									<th style="min-width: 110px;">题库类型</th>
									<th style="min-width: 90px;">题目数量</th>
									<th>简介</th>
									<th style="min-width: 250px;">操作</th>
								</tr>
							</thead>
							<tbody>
                                {% for bank in banks %}
								<tr data-bankid = "{{ bank.uuid }}">
									<td>{{ bank.uuid }}</td>
									<td>{{ bank.name }}</td>
									<td>{{ bank.get_type_display }}</td>
									<td>{{ bank.count }}</td>
									<td style="text-align: left;text-indent: 2em;">{{ bank.intro }}</td>
									<td>
										<a class="btn btn-blue" href="{% url 'exam:getquestion' %}?slug={{ bank.uuid }}" target="_blank"><i class="iconfont icon-tubiao09"></i>查阅试题</a>
										<a class="btn btn-red" href="{% url 'exam:deletebank' %}?slug={{ bank.uuid }}"><i class="iconfont icon-del"></i>删除</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				
			</div>
		</div>
		
		<div id="full-screen" style="display: none;"></div>
		
	</body>
</html>

templates/exam/candidateexams.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="shortcut icon" href="#"/>
		<title>考试信息</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/examinfo.css' %}"/>
		<script src="{% static 'js/jquery-3.1.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="content">
			<div class="container-left">
				<div class="author-info">
					<a href="#">
						<img src="{{ user.head_img.url }}"/>
					</a>
				</div>
				<p>学号：{{ user.username }}</p>
				<p>姓名：{{ user.name }}</p>
				<a href="{% url 'exam:student_index' %}" class="current">考试信息</a>
				<a href="{% url 'exam:history' %}">考试成绩</a>
                <a href="{% url 'role:logout' %}">退出登陆</a>
				
			</div>
			<div class="container-right">
				<div class="main">
					<ul>
                        {% for examiner in examiners %}
                        <li>
							<div class="box-left">
								<p class="box-title">{{ examiner.exam.title }}</p>
					 			<p class="box-date">考试时间: <span class="box-start-time">{{ examiner.exam.start_time|date:"Y-m-d H:i:s" }}</span> 至<span class="box-end-time">{{ examiner.exam.end_time|date:"Y-m-d H:i:s" }}</span></p>
					 			<p class="box-time">考试时长 : <span class="badge">{{ examiner.exam.time }}</span> 分钟</p>
							</div>
							<div class="box-right">
								<a href="{% url 'exam:exampaper' examiner.uuid %}" class="btn" style="width: 100px;">开始考试</a>
							</div>
						</li>
                        {% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</body>
	<script type="text/javascript">	

	</script>
</html>

templates/exam/exams.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="shortcut icon" href="#"/>
		<title>考试信息</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/conservator.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/exams.css' %}"/>
		<link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_1713310_k1bxcvlffm.css"/>
		<script src="{% static 'js/jquery-3.1.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/exams.js' %}" type="text/javascript" charset="utf-8"></script>

	</head>
	<body>
		<div class="manage-top">
			<p>在线考试系统教师管理</p>

			<div>
			    <span>
			    	<a class="a1" href="javascript:void(0)"><img src="{{ user.head_img.url }}"><font>{{ user.name }}</font></a>
			    	<ul style="display: none;">
{#			    		<li><a href="#"><i class="iconfont icon-people1"></i>个人中心</a></li>#}
{#			    		<li><a href="#"><i class="iconfont icon-password"></i>修改密码</a></li>#}
			    		<li><a href="{% url 'role:logout' %}"><i class="iconfont icon-logout1"></i>退出登录</a></li>
			    	</ul>
			    </span>
		   </div>

		</div>
		<div class="manage-content">
			<div class="mc-left">
				<div class="menuList">
					<ul class="menu1">
						<li class="menuli1">
							<a href="{% url 'exam:index' %}" class="menua1">
								<i class="iconfont icon-home1 left"></i>
								<p>教师管理主页</p>
							</a>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-candidates left"></i>
								<p>考生管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'role:students' %}" class="menua2">考生信息</a></li>
								<li class="menuli2"><a href="{% url 'role:addStudent' %}" class="menua2">添加考生</a></li>
								<li class="menuli2"><a href="{% url 'role:searchStudent' %}" class="menua2">查询信息</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-tiku1 left"></i>
								<p>题库管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:getbank' %}" class="menua2">题库列表</a></li>
								<li class="menuli2"><a href="{% url 'exam:addbank' %}" class="menua2">添加题库</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1 active-menu">
								<i class="iconfont icon-fenshijuan left"></i>
								<p>考试管理</p>
								<i class="iconfont icon-bottom right"></i>
							</a>
							<ul class="menu2" style="display: block;">
								<li class="menuli2"><a href="{% url 'exam:exams' %}" class="menua2 active-menu">考试信息</a></li>
								<li class="menuli2"><a href="{% url 'exam:exameditor' '' %}" class="menua2">添加考试</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="mc-right">
				<div class="mc-title">
					<font><a>考试管理</a><a>&gt;</a><a>考试信息</a></font>
				</div>
				<div class="mc-body" style="max-height: 525px; overflow-y: scroll;">
					<div class="mc-list">
						<table class="mc-table">
							<thead>
								<tr>
									<th style="min-width: 225px;">试卷名称</th>
									<th style="min-width: 100px;">考试总分</th>
									<th style="min-width: 100px;">及格分数</th>
									<th style="min-width: 100px;">答题时间</th>
									<th style="min-width: 330px;">考试时间</th>
									<th style="min-width: 90px;">状态</th>
									<th style="min-width: 190px;">操作</th>
								</tr>
							</thead>
							<tbody>
                            {% for exam in exams %}
								<tr data-examid = "{{ exam.uuid }}">
									<td>{{ exam.title }}</td>
									<td>{{ exam.total_socres }}分</td>
									<td>{{ exam.pass_score }}分</td>
									<td>{{ exam.time }}分钟</td>
									<td>
										<span>{{ exam.start_time|date:'Y-m-d H:i:s' }}</span>
										<span>&#126;</span>
										<span>{{ exam.end_time|date:'Y-m-d H:i:s' }}</span>
									</td>
									<td>{{ exam.get_status_display }}</td>
									<td class="option_btn">
                                        {% ifequal exam.status 'editor' %}
										    <a href="{% url 'exam:exameditor' exam.uuid %}" title="编辑考试内容"><i class="iconfont icon-tubiao09"></i>编辑</a>
                                            <a href="{% url 'exam:examdelete' exam.uuid %}" title="只可删除未发布的考试"><i class="iconfont icon-del"></i>删除</a>
                                        {% else %}
                                            <a href="{% url 'exam:examvisible' exam.uuid %}" title="是否允许学生可见已做试卷"><i class="iconfont icon-eye2"></i>可见</a>
                                            <a href="javascript:void(0);" onclick="alert('考试已发布，不可删除')" title="只可删除未发布的考试"><i class="iconfont icon-del"></i>删除</a>
                                        {% endifequal %}
									</td>
								</tr>
                            {% endfor %}
							</tbody>
						</table>
					</div>
				</div>

			</div>
		</div>

		<div id="full-screen" style="display: none;"></div>

	</body>
</html>

templates/exam/limit_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>超出次数</title>
</head>
<body style="text-align: center;padding: 0;margin: 0">
    <div style="position: relative">
        <div style="position: absolute;margin: auto;width: 600px; height: 380px;top: 400px;right: 0;bottom: 0;left: 0;text-align: left;">
            <p style="font-size: 16px">请求试卷超出5次，无法再次请求，如有需要，请联系管理员</p>
            <p style="font-size: 16px">点击&nbsp;<a href="{% url 'exam:student_index' %}">返回</a>&nbsp;上一页</p>
        </div>
    </div>
</body>
</html>