exam/urls.py
from django.urls import path, re_path, include
from exam.views import *

urlpatterns = [
    path('teacherindex', GetTeacherIndex.as_view(), name="index"),
    path('banks', GetQuestionBank.as_view(), name='getbank'),
    path('addbank', AddQuestionBank.as_view(), name='addbank'),
    path('deletebank', DeleteQuestionBank.as_view(), name='deletebank'),
    path('questions', GetQuestions.as_view(), name='getquestion'),
    path('addquestion', AddQuestion.as_view()),
    path('importquestion', BatchAddQuestion.as_view()),
    path('getquestion', GetQuestion.as_view()),
    path('deletetopicimg', DeleteTopicImg.as_view()),
    path('deletequestion', DeleteQuestion.as_view()),
    re_path('searchquestion/(?P<slug>[0-9]{10})', SearchQuestion.as_view(), name='search_question'),
    path('exams', GetExaminationList.as_view(), name='exams'),
    # path('exameditor', ExamEditor.as_view(), name='exameditor'),
    re_path('exameditor/(?P<exam_uuid>[a-z0-9]{0,10})', ExamEditor.as_view(), name='exameditor'),
    re_path('examdesign/(?P<exam_uuid>[a-z0-9]{10})', ExamDesign.as_view(), name='examdesign'),
    path('getSelectQuestions', GetSelectQuestions.as_view()),
    path('selectquestions', SelectQuestionsAjax.as_view()),
    path('setstaticquestionscore', SetStaticQuestionScore.as_view()),
    path('deletestaticquestion', DeleteStaticQuestion.as_view()),
    path('addrandomnode', AddRandomNodeAjax.as_view()),
    path('questiontypechange', QuestionTypeChange.as_view()),
    path('questionbankchange', QuestionBankChange.as_view()),
    path('questionnumberset', QuestionNumberSet.as_view()),
    path('questionscoreset', QuestionScoreSet.as_view()),
    path('deleterandomnode', DeleteRandomNodeAjax.as_view()),
    re_path('exampublish/(?P<exam_uuid>[a-z0-9]{10})', ExamPublish.as_view(), name='examdpublish'),
    re_path('examvisible/(?P<exam_uuid>[a-z0-9]{10})', AllowStudentsVisible.as_view(), name='examvisible'),
    re_path('examdelete/(?P<exam_uuid>[a-z0-9]{10})', DeleteExamination.as_view(), name='examdelete'),
    path('studentindex', GetStudentIndex.as_view(), name='student_index'),
    re_path('exam_paper/(?P<examiner_uuid>[a-z0-9]{10})', StartExam.as_view(), name='exampaper'),
    re_path('examhistorypapers/(?P<exam_uuid>[a-z0-9]{10})', GetAllStudentsPaper.as_view(), name='historypaperlist'),
    path('historyexam', GetHistoryExam.as_view(), name='history'),
    re_path('history_paper/(?P<examiner_uuid>[a-z0-9]{10})', GetHistoryPaper.as_view(), name='historypaper'),
]

onlineTestSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from role.views import Index, page_not_found
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', Index.as_view(), name="index"),
    re_path('^role/', include(('role.urls', 'role'), namespace='role')),
    re_path('^exam/', include(('exam.urls', 'exam'), namespace='exam')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

handler404 = page_not_found

role/urls.py
from django.urls import path, re_path, include
from role.views import *

urlpatterns = [
    path('logout', LoginOut.as_view(), name="logout"),
    path('get_valid_img', GetValidImg.as_view(), name='get_valid_img'),
    path('students', GetStudentInfo.as_view(), name='students'),
    path('addStudent', AddStudentInfo.as_view(), name='addStudent'),
    re_path('downloadexcel/(?P<excel_id>[a-z0-9]{1,10})', DownloadExcelTemplate.as_view(), name='downloadexcel'),
    path('uploadstudentfile', BatchAddStudents.as_view()),
    path('searchStudent', SearchStudentInfo.as_view(), name='searchStudent'),
    path('changeStudentStatus', ChangeStudentStatus.as_view()),
    path('editorStudentInfo', EditorStudentInfo.as_view()),
    path('deleteStudentInfo', DeleteStudentInfo.as_view()),
]

role/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from role.save import newStorage
from django.utils.timezone import now
# Create your models here.


class User(AbstractUser):
    sex_choice = (
        (u'male', u'男'),
        (u'female', u'女'),
        (u'nomale', u'保密'),
    )
    job_choice = (
        (u'teacher', u'教师'),
        (u'student', u'学生'),
    )

    name = models.CharField('姓名', max_length=30, blank=True)
    sex = models.CharField('性别', max_length=6, choices=sex_choice, default='nomale')
    phone = models.CharField('手机', max_length=11, null=True, blank=True)
    role = models.CharField('职位', max_length=7, choices=job_choice)
    head_img = models.ImageField('头像', upload_to='head/%Y/%m/', storage=newStorage(), default='head/head_img.jfif')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息管理'
        ordering = ("-last_modified_time", "-created_time")
        indexes = [models.Index(fields=['username']),
                   models.Index(fields=['name'])]

    def __str__(self):
        return str(self.username)


class TeacherStudent(models.Model):
    teacher = models.ForeignKey(User, verbose_name='教师', related_name="teacher_up", on_delete=models.CASCADE)
    student = models.ForeignKey(User, verbose_name='学生', related_name="student_belong", on_delete=models.CASCADE)
    status = models.BooleanField('状态', default=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True,)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        unique_together = ('teacher', 'student',)
        verbose_name = '师生关系'
        verbose_name_plural = '师生关系管理'
        ordering = ("-last_modified_time", "-created_time")

    def __str__(self):
        return str(self.id)

role/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from role.codeimg import ValidCodeImg
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from role.MyPaginator import MyPaginator
from role.models import User, TeacherStudent
from django.db import transaction, IntegrityError
from django.db.models import Q
from exam.models import ExcelTemplates
import json
from django.http import FileResponse
from django.utils.http import urlquote
from exam.img_save import SaveImg
from xlrd import open_workbook
from xlwt import Workbook
# Create your views here.


def page_not_found(request, exception, template_name='role/404.html'):
    return render(request, template_name)


class LoginRequiredMixin(object):
    """登录状态校验"""
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class LoginOut(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect("index")


class Index(View):
    def get(self, request):
        if request.user.is_authenticated:
            if request.user.role == 'teacher':
                return redirect("exam:index")
            else:
                return redirect("exam:student_index")
        else:
            err = ""
            return render(request, "role/login.html", {"err":err})

    def post(self, request):
        name = request.POST.get('name')
        password = request.POST.get('password')
        rol = request.POST.get('role')
        code = request.POST.get('code')
        err = ""
        if not name and not password and not code:
            err = "学号/工号、密码、验证码不能为空"
        elif code.upper() != request.session.get('valid_code').upper():
            err = "验证码错误"
        else:
            user = authenticate(request, username=name, password=password)
            if user:
                if user.role == rol:
                    login(request, user)
                    if user.role == 'teacher':
                        return redirect("exam:index")
                    else:
                        return redirect("exam:student_index")
                else:
                    err = "角色选择有误"
            else:
                err = "学号/工号或密码错误"
        return render(request, 'role/login.html',{"err": err})


class GetValidImg(View):

    def get(self, request):
        img = ValidCodeImg(width=80, height=32, code_count=4)
        img_data, valid_code = img.getValidCodeImg()
        request.session['valid_code'] = valid_code
        return HttpResponse(img_data)


class GetStudentInfo(LoginRequiredMixin, View):

    def get(self, request):
        students = TeacherStudent.objects.filter(teacher=request.user)
        context = MyPaginator(students, request, 9).paginator()
        students = context['query']
        pages = context['pages']
        return render(request, 'role/students.html', {"students": students, "pages": pages})


class AddStudentInfo(LoginRequiredMixin, View):

    def get(self, request):
        excel = ExcelTemplates.objects.get(is_static=True, type='st')
        return render(request, 'role/studentadd.html', {"message": "", "excel": excel})

    def post(self, request):
        username = request.POST.get('stuId')
        password = request.POST.get('password')
        cpassword = request.POST.get('cpassword')
        name = request.POST.get('name')
        sex = request.POST.get('sex')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        message = ""
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            if username and password:
                if password == cpassword:
                    teacher = request.user
                    try:
                        with transaction.atomic():
                            student = User.objects.create_user(username=username, password=password, name=name, sex=sex, phone=phone, email=email, role='student')
                            TeacherStudent.objects.create(teacher=teacher, student=student)
                    except IntegrityError:
                        message = "添加失败，请重试"
                    else:
                        message = "添加成功，成功加入 {} 组".format(teacher.name)
                else:
                    message = "添加失败：两次输入的密码不一致"
            else:
                message = "添加失败：学号或密码为空"
        else:
            teacher = request.user
            student = User.objects.get(username=username)
            try:
                TeacherStudent.objects.get(teacher=teacher, student=student)
            except TeacherStudent.DoesNotExist:
                TeacherStudent.objects.create(teacher=teacher, student=student)
                message = "添加成功：该用户已存在，成功加入 {} 组".format(teacher.name)
            else:
                message = "添加失败：该用户在 {} 组中".format(teacher.name)
        excel = ExcelTemplates.objects.get(is_static=True, type='st')
        return render(request, 'role/studentadd.html', {"message": message, "excel": excel})


class DownloadExcelTemplate(LoginRequiredMixin, View):
    def get(self, request, excel_id):
        if excel_id.isdigit():
            filename = 'media/' + str(ExcelTemplates.objects.get(id=excel_id, is_static=False).file)
        else:
            filename = 'media/' + str(get_object_or_404(ExcelTemplates, is_static=True, type=excel_id).file)
        thefilename = filename.split("/")[-1]
        file = open(filename, 'rb')
        response = FileResponse(file)
        response['Content-Disposition'] = 'attachment;filename="%s"' % urlquote(thefilename)
        return response


class BatchAddStudents(LoginRequiredMixin, View):
    def post(self, request):
        file = request.FILES.get('file', None)
        from uuid import uuid1
        save_path = SaveImg().excel_save(file, 'excel')
        readboot = open_workbook(save_path)
        sheet = readboot.sheet_by_index(0)
        # 获取excel的行和列
        nrows = sheet.nrows
        ncols = sheet.ncols
        row = sheet.row_values(0)
        row.append("结果")
        write_list = []
        write_list.append(row)
        for i in range(1, nrows):
            row = sheet.row_values(i)
            username = row[0]
            if type(username) is not str:
                username = str(int(float(username)))
            password = row[1]
            if type(password) is not str:
                password = str(int(float(password)))
            name = row[2]
            sex = row[3]
            if sex == '男':
                sex = 'male'
            elif sex == '女':
                sex = 'female'
            else:
                sex = 'nomale'
            phone = row[4]
            if type(phone) is not str:
                phone = str(int(float(phone)))
            email = row[5]
            try:
                student = User.objects.get(username=username)
            except User.DoesNotExist:
                try:
                    with transaction.atomic():
                        student = User.objects.create_user(username=username, password=password, name=name, sex=sex,
                                                           phone=phone, email=email, role='student')
                        TeacherStudent.objects.create(teacher=request.user, student=student)
                except IntegrityError:
                    row.append("添加失败")
                else:
                    row.append("添加成功，成功加入组")
            else:
                try:
                    TeacherStudent.objects.get(teacher=request.user, student=student)
                except TeacherStudent.DoesNotExist:
                    TeacherStudent.objects.create(teacher=request.user, student=student)
                    row.append("用户已存在，成功加入组")
                else:
                    row.append("用户已在组内，不可重复添加")
            finally:
                write_list.append(row)
        SaveImg().delete_question_img(save_path)
        workbook = Workbook(encoding='utf-8')
        sheet = workbook.add_sheet('sheet1')
        for i in range(len(write_list)):
            for j in range(len(write_list[0])):
                sheet.write(i, j, write_list[i][j])
        path = SaveImg().get_img_path('excel') + str(uuid1()) + ".xls"
        workbook.save(path)
        excel = ExcelTemplates.objects.create(name='考生信息批量上传模板-结果', type='st', file=path.split("media\\")[-1])
        host = request.get_host()
        address = 'http://' + host + '/role/downloadexcel/' + str(excel.id)
        return HttpResponse(json.dumps({"status": 1, "address": address}))


class SearchStudentInfo(LoginRequiredMixin, View):

    def get(self, request):
        username = request.GET.get('searchid')
        if username is None:
            search_id = ""
        else:
            search_id = username
        name = request.GET.get('searchname')
        if name is None:
            search_name = ""
        else:
            search_name = name
        if username and name:
            students = TeacherStudent.objects.filter(
                Q(student__name__icontains=name) | Q(student__username__icontains=username), teacher=request.user)
        elif username:
            students = TeacherStudent.objects.filter(Q(student__username__icontains=username), teacher=request.user)
        elif name:
            students = TeacherStudent.objects.filter(Q(student__name__icontains=name), teacher=request.user)
        else:
            students = TeacherStudent.objects.filter(id=0)
        context = MyPaginator(students, request, 8).paginator()
        students = context['query']
        pages = context['pages']
        return render(request, 'role/studentsearch.html',
                      {"students": students, "pages": pages, "searchid": search_id, "searchname": search_name})

templates/role/login.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="#"/>
    <title>在线考试系统-登录</title>
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    
</head>
<body>
    <div class="bg"></div>
    <div class="container">
        <div class="line bouncein">
            <div class="xs6 xm4 xs3-move xm4-move">
                <div style="height:60px;"></div>
                <div class="media media-y margin-big-bottom">
                </div>
                <form action="{% url 'index' %}" method="post">{% csrf_token %}
                    <div class="panel loginbox">
                        <div class="text-center margin-big padding-big-top">
                            <h1>在线考试系统登陆</h1>
                        </div>
                        <div class="panel-body" style="padding:30px; padding-bottom:10px; padding-top:10px;">
                            <div class="form-group">
                                <div class="field field-icon-right">
                                    <input type="text" class="input input-big" name="name" id="username" placeholder="学号/工号" />
                                    <span class="icon icon-user margin-small"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="field field-icon-right">
                                    <input type="password" class="input input-big" name="password" id="password"  placeholder="请输入密码" />
                                    <span class="icon icon-key margin-small"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="field field-icon-right">
                                    <select class="input input-big" name="role" id="role">
                                    	<option value="student">学生</option>
                                    	<option value="teacher">教师</option>
                                    </select>
                                    <span class="icon icon-users margin-small" style="background-color: white;"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="field">
                                    <input type="text" class="input input-big" name="code" placeholder="填写右侧的验证码" />
                                    <img src="role/get_valid_img" alt="" class="passcode" style="height:44px;cursor:pointer;" onclick="this.src=this.src+'?'" title="点击换一个">
                                </div>
                            </div>
                        </div>
                       {% if err %}
                       <div style="text-align: center;color: red;font-size: 16px;">
                        	<span class="icon icon-warning"></span>{{ err }}
                        </div>
                       {% endif %}
                        <div style="padding:30px;">
                            <input type="submit" id="button" class="button button-block bg-main text-big input-big" value="登录">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/role/studentadd.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="shortcut icon" href="#"/>
		<title>添加考生</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/conservator.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/add_student.css' %}"/>
		<link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_1713310_k1bxcvlffm.css"/>
		<script src="{% static 'js/jquery-3.1.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/add-student-info.js' %}" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="manage-top">
			<p>在线考试系统教师管理</p>
			
			<div>
			    <span>
			    	<a class="a1" href="javascript:void(0)"><img src="{{ user.head_img.url }}"><font>{{ user.name }}</font></a>
			    	<ul style="display: none;">
{#			    		<li><a href="#"><i class="iconfont icon-people1"></i>个人中心</a></li>#}
{#			    		<li><a href="#"><i class="iconfont icon-password"></i>修改密码</a></li>#}
			    		<li><a href="{% url 'role:logout' %}"><i class="iconfont icon-logout1"></i>退出登录</a></li>
			    	</ul>
			    </span>
		   </div>
			
		</div>
		<div class="manage-content">
			<div class="mc-left">
				<div class="menuList">
                    <ul class="menu1">
						<li class="menuli1">
							<a href="{% url 'exam:index' %}" class="menua1">
								<i class="iconfont icon-home1 left"></i>
								<p>教师管理主页</p>
							</a>

						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1 active-menu">
								<i class="iconfont icon-candidates left"></i>
								<p>考生管理</p>
								<i class="iconfont icon-bottom right"></i>
							</a>
							<ul class="menu2" style="display: block;">
								<li class="menuli2"><a href="{% url 'role:students' %}" class="menua2">考生信息</a></li>
								<li class="menuli2"><a href="{% url 'role:addStudent' %}" class="menua2 active-menu">添加考生</a></li>
								<li class="menuli2"><a href="{% url 'role:searchStudent' %}" class="menua2">查询信息</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-tiku1 left"></i>
								<p>题库管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:getbank' %}" class="menua2">题库列表</a></li>
								<li class="menuli2"><a href="{% url 'exam:addbank' %}" class="menua2">添加题库</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-fenshijuan left"></i>
								<p>考试管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:exams' %}" class="menua2">考试信息</a></li>
								<li class="menuli2"><a href="{% url 'exam:exameditor' '' %}" class="menua2">添加考试</a></li>
							</ul>
						</li>
					</ul>
                </div>
			</div>
			<div class="mc-right">
				<div class="mc-title">
					<font><a>考生管理</a><a>&gt;</a><a>考生信息</a></font>
				</div>
				<div class="mc-body">
					
					<div class="mc-per-add">
						<form action="{% url 'role:addStudent' %}" method="post" onsubmit="perAddStudentInfo()">{% csrf_token %}
							<div class="add-ul-left">
								<ul>
									<li>学号</li>
									<li>密码</li>
									<li>确认密码</li>
									<li>姓名</li>
									<li>性别</li>
									<li>手机号</li>
									<li>邮箱</li>
								</ul>
							</div>
							<div class="add-ul-right">
								<ul>
									<li><input type="text" name="stuId" placeholder="请输入学号" /><span class="warn-start">*</span></li>
									<li><input type="password" name="password" placeholder="请输入密码" /><span class="warn-start">*</span><span><i class="iconfont icon-eye-on"></i></span></li>
									<li><input type="password" name="cpassword" placeholder="请再次输入密码" /><span class="warn-start">*</span><span><i class="iconfont icon-eye-on"></i></span></li>
									<li><input type="text" name="name" placeholder="请输入姓名" /></li>
									<li class="sex-size">
										<input type="radio" name="sex" value="male" /><span>男</span>
										<input type="radio" name="sex" value="female" /><span>女</span>
										<input type="radio" name="sex" value="nomale" checked="checked"/><span>保密</span>
									</li>
									<li><input type="text" name="phone" placeholder="请输入手机号" /></li>
									<li><input type="email" name="email" placeholder="请输入邮箱" /></li>
								</ul>
							</div>
							<button type="submit" class="make-sure-add">确认添加</button>

						</form>
					</div>
					<div class="mc-batch-add">
						
						<div class="add-batch">
							<p>批量导入考生信息</p>
							<form action="." method="post">
								<p><input type="file" name="uploadfile" /></p>
								<p>导入模板下载：<span><a href="{% url 'role:downloadexcel' 'st' %}" style="color: #2b71c8">{{ excel.name }}.xlsx</a></span></p>
								<p><button type="button">提交</button></p>
							</form>
						</div>
						
					</div>
				</div>
				
			</div>
		</div>
		
	
	</body>
    <script>
        window.onload=function () {
            var message = "{{ message }}";
            if (message){
                alert(message);
            }
        }
    </script>

</html>

templates/role/students.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="shortcut icon" href="#"/>
		<title>考生信息</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/conservator.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/student_info.css' %}"/>
		<link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_1713310_k1bxcvlffm.css"/>
		<script src="{% static 'js/jquery-3.1.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/editor-student-info.js' %}" type="text/javascript" charset="utf-8"></script>

	</head>
	<body>
		<div class="manage-top">
			<p>在线考试系统教师管理</p>
				
			<div>
			    <span>
			    	<a class="a1" href="javascript:void(0)"><img src="{{ user.head_img.url }}"><font>{{ user.name }}</font></a>
			    	<ul style="display: none;">
{#			    		<li><a href="#"><i class="iconfont icon-people1"></i>个人中心</a></li>#}
{#			    		<li><a href="#"><i class="iconfont icon-password"></i>修改密码</a></li>#}
			    		<li><a href="{% url 'role:logout' %}"><i class="iconfont icon-logout1"></i>退出登录</a></li>
			    	</ul>
			    </span>
		   </div>
			
		</div>
		<div class="manage-content">
			<div class="mc-left">
				<div class="menuList">
                    <ul class="menu1">
						<li class="menuli1">
							<a href="{% url 'exam:index' %}" class="menua1">
								<i class="iconfont icon-home1 left"></i>
								<p>教师管理主页</p>
							</a>

						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1 active-menu">
								<i class="iconfont icon-candidates left"></i>
								<p>考生管理</p>
								<i class="iconfont icon-bottom right"></i>
							</a>
							<ul class="menu2" style="display: block;">
								<li class="menuli2"><a href="{% url 'role:students' %}" class="menua2 active-menu">考生信息</a></li>
								<li class="menuli2"><a href="{% url 'role:addStudent' %}" class="menua2">添加考生</a></li>
								<li class="menuli2"><a href="{% url 'role:searchStudent' %}" class="menua2">查询信息</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-tiku1 left"></i>
								<p>题库管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:getbank' %}" class="menua2">题库列表</a></li>
								<li class="menuli2"><a href="{% url 'exam:addbank' %}" class="menua2">添加题库</a></li>
							</ul>
						</li>
						<li class="menuli1">
							<a href="javascript:void(0);" class="menua1">
								<i class="iconfont icon-fenshijuan left"></i>
								<p>考试管理</p>
								<i class="iconfont icon-left1 right"></i>
							</a>
							<ul class="menu2" style="display: none;">
								<li class="menuli2"><a href="{% url 'exam:exams' %}" class="menua2">考试信息</a></li>
								<li class="menuli2"><a href="{% url 'exam:exameditor' '' %}" class="menua2">添加考试</a></li>
							</ul>
						</li>
					</ul>
                </div>
			</div>
			<div class="mc-right">
				<div class="mc-title">
					<font><a>考生管理</a><a>&gt;</a><a>考生信息</a></font>
				</div>
				<div class="mc-body">
					<div class="mc-list">
						<table class="mc-table">
							<thead>
								<tr>
									<th style="min-width: 120px;">学号</th>
									<th style="min-width: 90px;">姓名</th>
									<th style="min-width: 60px;">性别</th>
									<th style="min-width: 140px;">手机号</th>
									<th style="max-width: 120px;">邮箱</th>
									<th>状态</th>
									<th style="min-width: 170px;">操作</th>
								</tr>
							</thead>
							<tbody>
                                {% for student in students %}
                                    <tr data-stuid = "{{ student.student.username }}">
                                        <td>{{ student.student.username }}</td>
                                        <td>{{ student.student.name }}</td>
                                        <td>{{ student.student.get_sex_display }}</td>
                                        <td>{{ student.student.phone }}</td>
                                        <td>{{ student.student.email }}</td>
                                        <td class="Switch">
                                            {% if student.status %}
                                                <input type="checkbox" name="Storage{{ student.id }}" id="blance{{ student.id }}" checked="true">
                                            {% else %}
                                                <input type="checkbox" name="Storage{{ student.id }}" id="blance{{ student.id }}">
                                            {% endif %}
                                            <label for="blance{{ student.id }}"><em></em></label>
                                        </td>
                                        <td>
                                            <button class="mctb-button editor-stu-info"><i class="iconfont icon-tubiao09"></i>编辑</button>
                                            <button class="mctb-button delete-stu-info"><i class="iconfont icon-del"></i>删除</button>
                                        </td>
                                    </tr>
                                 {% endfor %}
							</tbody>
						</table>
					</div>
					<div class="mc-page-card">
						<ul class="c-pager">
							<li class="ys-pager-btn"><a href="?page={{ 1 }}">首页</a></li>
                            {% if students.has_previous %}
                                <li class="ys-pager-btn"><a href="?page={{ students.previous_page_number }}">上一页</a></li>
                            {% endif %}
                            {% for page in pages %}
                                <li class="ys-pager-item {% if students.number == page %}ys-cur-pager{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                            {% endfor %}
                            {% if students.has_next %}
							    <li class="ys-pager-btn"><a href="?page={{ students.next_page_number }}">下一页</a></li>
                            {% endif %}
							<li class="ys-pager-btn"><a href="?page={{ students.paginator.num_pages }}">尾页</a></li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
		
		<div id="full-screen" style="display: none;"></div>
		
	</body>
</html>